const DAYS=['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'];
const EN_DAYS=['Saturday','Sunday','Monday','Tuesday','Wednesday','Thursday','Friday'];
const FIXED={
  'شنبه':[['07:00','15:00','مدرسه','school'],['19:00','22:00','باشگاه','gym']],
  'یکشنبه':[['07:00','15:00','مدرسه','school'],['16:00','21:00','زبان','language']],
  'دوشنبه':[['07:00','15:00','مدرسه','school'],['19:00','22:00','باشگاه','gym']],
  'سه‌شنبه':[['07:00','15:00','مدرسه','school'],['16:00','21:00','زبان','language']],
  'چهارشنبه':[['07:00','15:00','مدرسه','school'],['19:00','22:00','باشگاه','gym']],
  'پنجشنبه':[['16:00','21:00','زبان','language']],
  'جمعه':[]
};
const TIKTOK=[['شنبه','فیلم اجرای کوتاه گیتار'],['یکشنبه','ادیت و انتخاب بهترین قسمت‌ها'],['دوشنبه','ضبط محتوای تکنیک گیتار'],['سه‌شنبه','ایده‌پردازی + اسکریپت'],['چهارشنبه','ضبط و آماده‌سازی ویدیو'],['پنجشنبه','ادیت + کاور + کپشن'],['جمعه','مرور ویدیوهای هفته + ایده‌پردازی']];
const GUITAR=[['شنبه','Alternate Picking + Song'],['یکشنبه','Chords + Chord Changes'],['دوشنبه','Legato + Song'],['سه‌شنبه','Bending + Vibrato'],['چهارشنبه','Alternate Picking + Song'],['پنجشنبه','Theory + Fretboard'],['جمعه','Weekly Review + Record Practice']];
const SUBJECT_METHODS={
  'ریاضی':['درک مفهوم','حل دوباره مثال بدون نگاه','۳ تا ۵ مسئله مشابه','ثبت اشتباهات','مرور اشتباهات'],
  'هندسه':['رسم شکل','شناسایی داده‌ها','مشخص کردن هدف اثبات','درک قضیه','نوشتن اثبات مرحله‌به‌مرحله'],
  'فیزیک':['درک مفهوم','نوشتن داده‌ها','مشخص کردن هدف','انتخاب فرمول','بررسی واحدها','حل مسئله'],
  'شیمی':['درک مفاهیم','مرور فرمول‌ها/واکنش‌های مهم','حل مثال','تمرین محاسبات','مرور فاصله‌دار'],
  'عربی':['مرور واژگان','گرامر با مثال','ترجمه','تمرین','ثبت اشتباهات گرامری'],
  'فارسی':['درک مطلب','واژگان','آرایه‌های ادبی','گرامر','خودآزمایی']
};
const WORKOUT_A=['Warm-up 5–10 min','Machine Chest Press 2×10–12','Lat Pulldown 2×10–12','Leg Press 2×10–12','Leg Curl 2×10–12','Seated Row 2×10–12','Plank 2×20–40 sec'];
const WORKOUT_B=['Warm-up 5–10 min','Machine Shoulder Press 2×10–12','Seated Row 2×10–12','Light Squat 2×8–12','Leg Curl 2×10–12','Light Lateral Raise 2×10–15','Dead Bug 2×8–12 each side'];
const I18N={
  fa:{brandSub:'داشبورد شخصی تو',navHome:'خانه',navPlan:'برنامه',navAI:'دستیار AI',navProgress:'پیشرفت',navSettings:'تنظیمات',hello:'سلام آرتیمان 👋',weekLine:'بیا این هفته رو بهتر از هفته قبل بسازیم 🚀',todayProgress:'پیشرفت امروز',tasksDone:'کارهای انجام‌شده',tasksLeft:'کارهای باقی‌مانده',week:'هفته جاری',weekly:'تکمیل هفتگی',nextPlan:'🤖 برنامه هفته بعد',aiChecking:'دستیار AI در حال بررسی پیشرفت هفته است...',aiUnavailable:'اتصال AI در دسترس نیست؛ برنامه فعلی همچنان قابل استفاده است.',study:'مطالعه',guitar:'گیتار',gym:'باشگاه',tiktok:'TikTok',today:'امروز',openPlan:'باز کردن برنامه',save:'ذخیره',cancel:'لغو',offline:'آفلاین',online:'آنلاین',fixed:'ثابت',flexible:'انعطاف‌پذیر',confirm:'تأیید',apply:'اعمال برنامه',settings:'تنظیمات',language:'زبان',theme:'تم',notifications:'اعلان‌ها',backend:'آدرس Backend',apiWarning:'کلید API نباید داخل اپلیکیشن ذخیره شود.',privacy:'اطلاعات خصوصی',reset:'ریست پیشرفت هفته',export:'خروجی JSON',aiTitle:'🤖 دستیار آرتیمان',aiHint:'مثلاً: امروز خیلی خسته‌ام، چیکار کنم؟',send:'ارسال',assistantOffline:'پاسخ آفلاین',noBackend:'Backend تنظیم نشده است؛ پاسخ‌ها از راهنمای آفلاین برنامه می‌آیند.',backEndSaved:'آدرس Backend ذخیره شد',daily:'روزانه',streak:'استریک',missed:'از دست رفته',completed:'تکمیل شده',confirmNew:'تأیید برنامه جدید',copyContext:'وضعیت فعلی',privacyText:'نام کامل، نام مدرسه، آدرس دقیق، شماره تلفن، لوکیشن زنده یا اطلاعات خصوصی را وارد یا منتشر نکن.',rest:'استراحت',school:'مدرسه',languageClass:'زبان',recorded:'ضبط شده',edited:'ادیت شده',posted:'منتشر شده',focus:'تمرکز',methods:'روش مطالعه',form:'فرم صحیح مهم‌تر از وزنه سنگین است.',none:'هنوز چیزی ثبت نشده.'},
  en:{brandSub:'Your personal dashboard',navHome:'Home',navPlan:'Plan',navAI:'AI Assistant',navProgress:'Progress',navSettings:'Settings',hello:'Hi Artiman 👋',weekLine:"Let’s make this week better than the last 🚀",todayProgress:"Today's progress",tasksDone:'Completed tasks',tasksLeft:'Remaining tasks',week:'Current week',weekly:'Weekly completion',nextPlan:'🤖 Next week plan',aiChecking:'AI assistant is reviewing your weekly progress...',aiUnavailable:'AI connection is unavailable; the current plan still works.',study:'Study',guitar:'Guitar',gym:'Gym',tiktok:'TikTok',today:'Today',openPlan:'Open plan',save:'Save',cancel:'Cancel',offline:'Offline',online:'Online',fixed:'Fixed',flexible:'Flexible',confirm:'Confirm',apply:'Apply plan',settings:'Settings',language:'Language',theme:'Theme',notifications:'Notifications',backend:'Backend URL',apiWarning:'Never store an API key inside the app.',privacy:'Privacy',reset:'Reset weekly progress',export:'Export JSON',aiTitle:'🤖 Artiman Assistant',aiHint:'Example: I’m really tired today, what should I do?',send:'Send',assistantOffline:'Offline reply',noBackend:'No backend is configured; replies come from the offline guide.',backEndSaved:'Backend URL saved',daily:'Daily',streak:'Streak',missed:'Missed',completed:'Completed',confirmNew:'Confirm new plan',copyContext:'Current status',privacyText:'Do not enter or publish your full name, school name, exact address, phone number, live location, or other private personal information.',rest:'Rest',school:'School',languageClass:'Language',recorded:'Recorded',edited:'Edited',posted:'Posted',focus:'Focus',methods:'Study method',form:'Correct form matters more than heavy weight.',none:'Nothing logged yet.'}
};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const KEY='artiman-ai-web-v1';
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function weekId(d=new Date()){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())); const day=x.getUTCDay()||7; x.setUTCDate(x.getUTCDate()+4-day); const year=x.getUTCFullYear(); const first=new Date(Date.UTC(year,0,1)); const wk=Math.ceil((((x-first)/86400000)+1)/7); return `${year}-W${String(wk).padStart(2,'0')}`}
function getDayName(){return DAYS[(new Date().getDay()+1)%7]}
function initial(){const days={}; DAYS.forEach((d,i)=>{days[d]={tasks:[],fixed:FIXED[d]||[]}}); return {user:{name:'آرتیمان',age:15},weekId:weekId(),days,progress:{study:0,guitar:0,gym:0,tiktok:0},history:[],settings:{lang:'fa',theme:'dark',notifications:true,backend:''},chat:[{role:'bot',text:'سلام آرتیمان 👋 من دستیار آفلاین Artiman AI هستم. دربارهٔ درس، گیتار، باشگاه، TikTok و برنامه‌ریزی ازم بپرس.'}]}}
let state=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x)return x}catch{} return initial()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function t(k){return (I18N[state.settings.lang]||I18N.fa)[k]||k}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function pct(n){return Math.max(0,Math.min(100,Math.round(n)))}
function todayTaskList(){const d=state.days[getDayName()]; return d.tasks}
function allTasks(){return DAYS.flatMap(d=>state.days[d].tasks)}
function counts(){const a=allTasks();const done=a.filter(x=>x.completed).length;return {done,left:Math.max(0,a.length-done),total:a.length,pct:a.length?done/a.length*100:0}}
function ensureWeeklyTemplate(){
  if(!state.weekId){state.weekId=weekId()}
  if(state.weekId!==weekId()){
    state.history.push({weekId:state.weekId,progress:state.progress,days:state.days,archivedAt:new Date().toISOString()});
    state.weekId=weekId();state.days={};DAYS.forEach(d=>state.days[d]={tasks:[],fixed:FIXED[d]||[]});state.progress={study:0,guitar:0,gym:0,tiktok:0};
    DAYS.forEach((d,i)=>{addTask(d,'study',45);addTask(d,'guitar',45);addTask(d,'tiktok',45); if(['شنبه','دوشنبه','چهارشنبه'].includes(d)) addTask(d,'gym',180,true)});
    save();
  }
}
function addTask(day,category,duration,fixed=false){const title={study:t('study'),guitar:t('guitar'),tiktok:t('tiktok'),gym:t('gym')}[category]||category;state.days[day].tasks.push({id:uid(),title,category,day,duration,completed:false,fixed});}
function buildDefaultWeek(){DAYS.forEach(d=>{if(!state.days[d].tasks.length){addTask(d,'study',45);addTask(d,'guitar',45);addTask(d,'tiktok',45)}});save()}
ensureWeeklyTemplate();buildDefaultWeek();
function render(){renderHome();renderPlan();renderAI();renderProgress();renderSettings();applyLocale();}
function applyLocale(){document.documentElement.lang=state.settings.lang;document.documentElement.dir=state.settings.lang==='fa'?'rtl':'ltr';$$('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});document.title='Artiman AI';$('#langBtn').textContent=state.settings.lang==='fa'?'EN':'فا';document.documentElement.classList.toggle('light',state.settings.theme==='light');$('#themeBtn').textContent=state.settings.theme==='light'?'☀':'☾'}
function cardStat(emoji,label,value,progress){return `<div class="card stat-card"><div class="emoji">${emoji}</div><strong>${value}%</strong><small>${label}</small><div class="progress"><i style="width:${pct(progress)}%"></i></div></div>`}
function renderHome(){const c=counts();const d=todayTaskList();const dayDone=d.filter(x=>x.completed).length;const dayPct=d.length?dayDone/d.length*100:0; const missing=d.filter(x=>!x.completed).slice(0,4);
 $('#screen-home').innerHTML=`<div class="hero"><h1>${t('hello')}</h1><p>${t('weekLine')}</p><div class="section-title"><h2>${t('todayProgress')}</h2><span>${getDayName()}</span></div><div class="progress"><i style="width:${pct(dayPct)}%"></i></div><div class="row" style="margin-top:9px"><span class="mini">${dayDone}/${d.length} ${t('tasksDone')}</span><span class="mini">${pct(dayPct)}%</span></div></div>
 <div class="section-title"><h2>${t('focus')}</h2><span>${state.weekId}</span></div><div class="grid">${cardStat('📚',t('study'),Math.round(state.progress.study),state.progress.study)}${cardStat('🎸',t('guitar'),Math.round(state.progress.guitar),state.progress.guitar)}${cardStat('🏋️',t('gym'),Math.round(state.progress.gym),state.progress.gym)}${cardStat('🎬',t('tiktok'),Math.round(state.progress.tiktok),state.progress.tiktok)}</div>
 <div class="section-title"><h2>${t('tasksLeft')}</h2><span>${c.left}</span></div><div class="card">${missing.length?`<div class="task-list">${missing.map(x=>taskHTML(x,true)).join('')}</div>`:`<div class="empty">${state.settings.lang==='fa'?'عالیه؛ کارهای امروز کامل شده‌اند 💪':'Great job — today’s tasks are complete 💪'}</div>`}</div>
 <div class="section-title"><h2>${t('nextPlan')}</h2></div><div class="card"><strong>${state.settings.backend?t('aiChecking'):t('noBackend')}</strong><p class="mini" style="line-height:1.7;margin-bottom:0">${t('aiUnavailable')}</p></div>`}
function taskHTML(x,home=false){return `<label class="task"><input type="checkbox" data-task="${x.id}" ${x.completed?'checked':''}><div class="task-main"><div class="task-title">${esc(x.title)}</div><div class="task-meta">${x.duration} min · ${x.fixed?`<span class="tag fixed-badge">${t('fixed')}</span>`:`<span class="tag">${t('flexible')}</span>`}</div></div></label>`}
function renderPlan(){const selected=state.selectedDay||getDayName();state.selectedDay=selected;const d=state.days[selected];const fixed=(d.fixed||[]); const g=GUITAR[DAYS.indexOf(selected)]; const tk=TIKTOK[DAYS.indexOf(selected)];
 $('#screen-plan').innerHTML=`<div class="section-title"><h2>${t('navPlan')}</h2><span>${state.weekId}</span></div><div class="week-tabs">${DAYS.map((x,i)=>`<button class="day-tab ${x===selected?'active':''}" data-day="${x}"><b>${state.settings.lang==='fa'?x:EN_DAYS[i]}</b><small>${state.days[x].tasks.filter(q=>q.completed).length}/${state.days[x].tasks.length}</small></button>`).join('')}</div>
 <div class="section-title"><h2>${state.settings.lang==='fa'?'بازه‌های ثابت':'Fixed blocks'}</h2><span>${t('fixed')}</span></div><div class="card">${fixed.length?fixed.map(b=>`<div class="schedule-block"><div class="schedule-top"><span class="schedule-time">${b[0]}–${b[1]}</span><span class="tag fixed-badge">${b[2]}</span></div></div>`).join(''):`<div class="empty">${t('rest')}</div>`}</div>
 <div class="section-title"><h2>${state.settings.lang==='fa'?'کارهای انعطاف‌پذیر':'Flexible tasks'}</h2><span>45m+</span></div><div class="card"><div class="task-list">${d.tasks.map(x=>taskHTML(x)).join('')}</div><div class="section-title"><h2>🎸 ${t('guitar')} · 45m</h2></div><p class="mini">${esc(g?.[1]||'')}</p><div class="section-title"><h2>🎬 TikTok · 45m</h2></div><p class="mini">${esc(tk?.[1]||'')}</p></div>
 <div class="section-title"><h2>${state.settings.lang==='fa'?'مطالعه':'Study'}</h2></div><div class="card"><p class="mini">${state.settings.lang==='fa'?'موضوع هر روز می‌تواند براساس بازخورد هفته انتخاب شود؛ ساختار روش مطالعه در بخش زیر نگه داشته شده است.':'Daily subject can change from weekly feedback; the study method structure is kept below.'}</p>${Object.entries(SUBJECT_METHODS).map(([s,m])=>`<details><summary><strong>${s}</strong></summary><ul>${m.map(v=>`<li>${v}</li>`).join('')}</ul></details>`).join('')}</div>`;
}
function renderAI(){const msgs=state.chat.map(m=>`<div class="msg ${m.role}">${esc(m.text)}</div>`).join('');$('#screen-ai').innerHTML=`<div class="section-title"><h2>${t('aiTitle')}</h2><span>${state.settings.backend?t('online'):t('offline')}</span></div><div class="card chat"><div class="messages" id="messages">${msgs}</div><div class="composer"><textarea id="aiInput" placeholder="${t('aiHint')}"></textarea><button class="primary" id="sendAI">${t('send')}</button></div></div>`;const m=$('#messages');m.scrollTop=m.scrollHeight}
function renderProgress(){const c=counts();const cat={study:state.progress.study,guitar:state.progress.guitar,gym:state.progress.gym,tiktok:state.progress.tiktok};const bars=[...DAYS].map(d=>{const x=state.days[d].tasks;const p=x.length?x.filter(z=>z.completed).length/x.length*100:0;return `<div style="flex:1;min-width:22px"><div class="bar" style="height:${Math.max(8,p*1.55)}px"><small>${Math.round(p)}%</small></div><div class="bar-label">${state.settings.lang==='fa'?d.slice(0,2):EN_DAYS[DAYS.indexOf(d)].slice(0,2)}</div></div>`}).join('');$('#screen-progress').innerHTML=`<div class="section-title"><h2>📊 ${t('navProgress')}</h2><span>${state.weekId}</span></div><div class="kpi"><div class="kpi-box"><small>${t('completed')}</small><strong>${c.done}</strong></div><div class="kpi-box"><small>${t('missed')}</small><strong>${c.left}</strong></div><div class="kpi-box"><small>${t('weekly')}</small><strong>${Math.round(c.pct)}%</strong></div><div class="kpi-box"><small>${t('streak')}</small><strong>${calcStreak()}</strong></div></div><div class="section-title"><h2>${t('weekly')}</h2></div><div class="card"><div class="chart">${bars}</div></div><div class="section-title"><h2>${t('focus')}</h2></div><div class="grid">${Object.entries({study:'📚',guitar:'🎸',gym:'🏋️',tiktok:'🎬'}).map(([k,e])=>cardStat(e,t(k),Math.round(cat[k]),cat[k])).join('')}</div><div class="section-title"><h2>${t('form')}</h2></div><div class="card"><div class="mini">${t('privacyText')}</div><p style="margin-bottom:0">${state.settings.lang==='fa'?'امروز کامل نشد؛ فردا دوباره ادامه می‌دیم 💪':'Today wasn’t perfect; we’ll continue tomorrow 💪'}</p></div>`}
function calcStreak(){let s=0;for(const d of [...DAYS].reverse()){const tasks=state.days[d].tasks;if(tasks.length&&tasks.every(x=>x.completed))s++;else break}return s}
function renderSettings(){ $('#screen-settings').innerHTML=`<div class="section-title"><h2>⚙️ ${t('settings')}</h2></div><div class="settings-list"><div class="setting"><div class="setting-main"><strong>${t('language')}</strong><small>${state.settings.lang==='fa'?'فارسی / English':'English / فارسی'}</small></div><button class="secondary" id="settingLang">${state.settings.lang==='fa'?'English':'فارسی'}</button></div><div class="setting"><div class="setting-main"><strong>${t('theme')}</strong><small>${state.settings.theme==='dark'?'Dark':'Light'}</small></div><button class="secondary" id="settingTheme">${state.settings.theme==='dark'?'☀':'☾'}</button></div><div class="setting"><div class="setting-main"><strong>${t('notifications')}</strong><small>${state.settings.notifications?'On':'Off'}</small></div><label class="switch"><input id="notif" type="checkbox" ${state.settings.notifications?'checked':''}><span></span></label></div><div class="setting" style="display:block"><div class="setting-main"><strong>${t('backend')}</strong><small>${t('apiWarning')}</small></div><div style="display:flex;gap:8px;margin-top:10px"><input id="backend" value="${esc(state.settings.backend)}" placeholder="https://your-backend.example.com" style="flex:1;border-radius:13px;border:1px solid var(--border);background:rgba(0,0,0,.13);color:var(--text);padding:11px"><button class="primary" id="saveBackend">${t('save')}</button></div></div><div class="setting"><div class="setting-main"><strong>${t('privacy')}</strong><small>${t('privacyText')}</small></div><span>🔒</span></div><div class="setting"><div class="setting-main"><strong>${t('export')}</strong><small>JSON</small></div><button class="secondary" id="export">⬇</button></div><div class="setting"><div class="setting-main"><strong>${t('reset')}</strong><small>${state.settings.lang==='fa'?'هفته جاری را به حالت شروع برمی‌گرداند.':'Resets the current week.'}</small></div><button class="secondary danger" id="reset">↻</button></div></div>`}
function toast(msg){const x=$('#toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function switchScreen(name){$$('.screen').forEach(x=>x.classList.remove('active'));$('#screen-'+name).classList.add('active');$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.screen===name))}
function offlineReply(q){q=q.toLowerCase();const fa=state.settings.lang==='fa';if(q.includes('خسته')||q.includes('tired'))return fa?'امروز حجم کار را کم کن: یک کار درسی مهم، ۴۵ دقیقه گیتار با شدت متوسط و TikTok را در حد هدف پایه انجام بده. اگر خستگی زیاد است، استراحت و خواب را در اولویت بگذار.':'Reduce the load today: one important school task, a moderate 45-minute guitar session, and only the TikTok minimum. If you are very tired, prioritize rest and sleep.';if(q.includes('ریاضی')||q.includes('math'))return fa?'برای ریاضی: مفهوم را توضیح بده، یک مثال را بدون نگاه دوباره حل کن، سپس ۳ تا ۵ سؤال مشابه بزن و اشتباه‌هایت را ثبت کن.':'For math: explain the concept, redo one example without looking, solve 3–5 similar problems, then log your mistakes.';if(q.includes('alternate')||q.includes('پیک'))return fa?'۱۰ دقیقه گرم‌کردن کروماتیک، سپس alternate picking با مترونوم. تمیزی و هماهنگی را قبل از بالا بردن سرعت حفظ کن و از تمرینت یک ویدیو کوتاه ضبط کن.':'Do 10 minutes of chromatic warm-up, then alternate picking with a metronome. Keep it clean before increasing speed, and record a short practice clip.';if(q.includes('امروز برنامه')||q.includes("today"))return fa?`امروز ${getDayName()} است. ${todayTaskList().filter(x=>!x.completed).map(x=>x.title+' ('+x.duration+'دقیقه)').join('، ')||'همه کارها کامل شده‌اند.'}`:`Today is ${EN_DAYS[DAYS.indexOf(getDayName())]}. ${todayTaskList().filter(x=>!x.completed).map(x=>x.title+' ('+x.duration+' min)').join(', ')||'Everything is complete.'}`;return fa?'من در حالت آفلاین راهنمایی می‌کنم. می‌توانم براساس برنامه، کارهای امروز، مطالعه، گیتار، باشگاه و TikTok پیشنهاد ساده و عملی بدهم.':'I am in offline mode. I can still give practical guidance using your schedule, today’s tasks, study, guitar, gym, and TikTok plan.'}
async function askAI(text){state.chat.push({role:'user',text});save();renderAI();const typing={role:'bot',text:'…'};state.chat.push(typing);renderAI();const idx=state.chat.length-1;try{if(state.settings.backend){const r=await fetch(state.settings.backend.replace(/\/$/,'')+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,context:{weekId:state.weekId,days:state.days,progress:state.progress}})});if(!r.ok)throw new Error('backend');const j=await r.json();state.chat[idx]={role:'bot',text:j.response||t('aiUnavailable')}}else{await new Promise(r=>setTimeout(r,500));state.chat[idx]={role:'bot',text:offlineReply(text)}}}catch(e){state.chat[idx]={role:'bot',text:t('aiUnavailable')+' '+offlineReply(text)}}save();renderAI()}
function applyBindings(){document.addEventListener('click',e=>{const nav=e.target.closest('.nav-btn');if(nav){switchScreen(nav.dataset.screen);return}const tab=e.target.closest('.day-tab');if(tab){state.selectedDay=tab.dataset.day;renderPlan();return}if(e.target.id==='langBtn'||e.target.id==='settingLang'){state.settings.lang=state.settings.lang==='fa'?'en':'fa';save();render();return}if(e.target.id==='themeBtn'||e.target.id==='settingTheme'){state.settings.theme=state.settings.theme==='dark'?'light':'dark';save();render();return}if(e.target.id==='saveBackend'){state.settings.backend=$('#backend').value.trim();save();toast(t('backEndSaved'));renderSettings();return}if(e.target.id==='export'){download('artiman-ai-data.json',JSON.stringify(state,null,2),'application/json');return}if(e.target.id==='reset'){const fresh=initial();state.weekId=weekId();state.days=fresh.days;state.progress=fresh.progress;save();render();toast(state.settings.lang==='fa'?'هفته ریست شد':'Week reset');return}if(e.target.id==='sendAI'){const v=$('#aiInput')?.value.trim();if(v){$('#aiInput').value='';askAI(v)}return}});document.addEventListener('change',e=>{if(e.target.matches('[data-task]')){const x=allTasks().find(q=>q.id===e.target.dataset.task);if(x){x.completed=e.target.checked;recalcProgress();save();render()}}if(e.target.id==='notif'){state.settings.notifications=e.target.checked;save()}})}
function recalcProgress(){const map={study:0,guitar:0,gym:0,tiktok:0},tot={study:0,guitar:0,gym:0,tiktok:0};allTasks().forEach(x=>{if(map[x.category]!=null){tot[x.category]++;if(x.completed)map[x.category]++}});Object.keys(map).forEach(k=>state.progress[k]=tot[k]?map[k]/tot[k]*100:0)}
function download(name,data,type){const b=new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
applyBindings();render();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
